import 'package:city_repository/city_repository.dart';
import 'package:collection/collection.dart';

final cities = _cities.toSet().toList().sorted(
      (a, b) => a.name.compareTo(b.name),
    );

final _cities = [
  const City(name: 'New York', area: Area.usa),
  const City(name: 'Los Angeles', area: Area.usa),
  const City(name: 'Chicago', area: Area.usa),
  const City(name: 'Houston', area: Area.usa),
  const City(name: 'Phoenix', area: Area.usa),
  const City(name: 'Philadelphia', area: Area.usa),
  const City(name: 'San Antonio', area: Area.usa),
  const City(name: 'San Diego', area: Area.usa),
  const City(name: 'Dallas', area: Area.usa),
  const City(name: 'San Jose', area: Area.usa),
  const City(name: 'Austin', area: Area.usa),
  const City(name: 'Jacksonville', area: Area.usa),
  const City(name: 'Fort Worth', area: Area.usa),
  const City(name: 'Columbus', area: Area.usa),
  const City(name: 'San Francisco', area: Area.usa),
  const City(name: 'Charlotte', area: Area.usa),
  const City(name: 'Indianapolis', area: Area.usa),
  const City(name: 'Seattle', area: Area.usa),
  const City(name: 'Denver', area: Area.usa),
  const City(name: 'Washington', area: Area.usa),
  const City(name: 'Boston', area: Area.usa),
  const City(name: 'El Paso', area: Area.usa),
  const City(name: 'Nashville', area: Area.usa),
  const City(name: 'Detroit', area: Area.usa),
  const City(name: 'Oklahoma City', area: Area.usa),
  const City(name: 'Portland', area: Area.usa),
  const City(name: 'Las Vegas', area: Area.usa),
  const City(name: 'Memphis', area: Area.usa),
  const City(name: 'Louisville', area: Area.usa),
  const City(name: 'Baltimore', area: Area.usa),
  const City(name: 'Milwaukee', area: Area.usa),
  const City(name: 'Albuquerque', area: Area.usa),
  const City(name: 'Tucson', area: Area.usa),
  const City(name: 'Fresno', area: Area.usa),
  const City(name: 'Mesa', area: Area.usa),
  const City(name: 'Sacramento', area: Area.usa),
  const City(name: 'Atlanta', area: Area.usa),
  const City(name: 'Kansas City', area: Area.usa),
  const City(name: 'Colorado Springs', area: Area.usa),
  const City(name: 'Miami', area: Area.usa),
  const City(name: 'Raleigh', area: Area.usa),
  const City(name: 'Omaha', area: Area.usa),
  const City(name: 'Long Beach', area: Area.usa),
  const City(name: 'Virginia Beach', area: Area.usa),
  const City(name: 'Oakland', area: Area.usa),
  const City(name: 'Minneapolis', area: Area.usa),
  const City(name: 'Tulsa', area: Area.usa),
  const City(name: 'Arlington', area: Area.usa),
  const City(name: 'New Orleans', area: Area.usa),
  const City(name: 'Wichita', area: Area.usa),
  const City(name: 'Bakersfield', area: Area.usa),
  const City(name: 'Cleveland', area: Area.usa),
  const City(name: 'Aurora', area: Area.usa),
  const City(name: 'Anaheim', area: Area.usa),
  const City(name: 'Honolulu', area: Area.usa),
  const City(name: 'Santa Ana', area: Area.usa),
  const City(name: 'Riverside', area: Area.usa),
  const City(name: 'Corpus Christi', area: Area.usa),
  const City(name: 'Lexington', area: Area.usa),
  const City(name: 'Henderson', area: Area.usa),
  const City(name: 'Stockton', area: Area.usa),
  const City(name: 'Saint Paul', area: Area.usa),
  const City(name: 'Cincinnati', area: Area.usa),
  const City(name: 'St. Louis', area: Area.usa),
  const City(name: 'Pittsburgh', area: Area.usa),
  const City(name: 'Greensboro', area: Area.usa),
  const City(name: 'Lincoln', area: Area.usa),
  const City(name: 'Anchorage', area: Area.usa),
  const City(name: 'Plano', area: Area.usa),
  const City(name: 'Orlando', area: Area.usa),
  const City(name: 'Irvine', area: Area.usa),
  const City(name: 'Newark', area: Area.usa),
  const City(name: 'Toledo', area: Area.usa),
  const City(name: 'Durham', area: Area.usa),
  const City(name: 'Chula Vista', area: Area.usa),
  const City(name: 'Fort Wayne', area: Area.usa),
  const City(name: 'Jersey City', area: Area.usa),
  const City(name: 'St. Petersburg', area: Area.usa),
  const City(name: 'Laredo', area: Area.usa),
  const City(name: 'Madison', area: Area.usa),
  const City(name: 'Chandler', area: Area.usa),
  const City(name: 'Buffalo', area: Area.usa),
  const City(name: 'Lubbock', area: Area.usa),
  const City(name: 'Scottsdale', area: Area.usa),
  const City(name: 'Reno', area: Area.usa),
  const City(name: 'Glendale', area: Area.usa),
  const City(name: 'Gilbert', area: Area.usa),
  const City(name: 'Winston–Salem', area: Area.usa),
  const City(name: 'North Las Vegas', area: Area.usa),
  const City(name: 'Norfolk', area: Area.usa),
  const City(name: 'Chesapeake', area: Area.usa),
  const City(name: 'Garland', area: Area.usa),
  const City(name: 'Irving', area: Area.usa),
  const City(name: 'Hialeah', area: Area.usa),
  const City(name: 'Fremont', area: Area.usa),
  const City(name: 'Boise', area: Area.usa),
  const City(name: 'Richmond', area: Area.usa),
  const City(name: 'Baton Rouge', area: Area.usa),
  const City(name: 'Spokane', area: Area.usa),
  const City(name: 'Des Moines', area: Area.usa),
  const City(name: 'Tacoma', area: Area.usa),
  const City(name: 'San Bernardino', area: Area.usa),
  const City(name: 'Modesto', area: Area.usa),
  const City(name: 'Fontana', area: Area.usa),
  const City(name: 'Santa Clarita', area: Area.usa),
  const City(name: 'Birmingham', area: Area.usa),
  const City(name: 'Oxnard', area: Area.usa),
  const City(name: 'Fayetteville', area: Area.usa),
  const City(name: 'Rochester', area: Area.usa),
  const City(name: 'Moreno Valley', area: Area.usa),
  const City(name: 'Glendale', area: Area.usa),
  const City(name: 'Yonkers', area: Area.usa),
  const City(name: 'Huntington Beach', area: Area.usa),
  const City(name: 'Aurora', area: Area.usa),
  const City(name: 'Salt Lake City', area: Area.usa),
  const City(name: 'Amarillo', area: Area.usa),
  const City(name: 'Montgomery', area: Area.usa),
  const City(name: 'Little Rock', area: Area.usa),
  const City(name: 'Akron', area: Area.usa),
  const City(name: 'Grand Rapids', area: Area.usa),
  const City(name: 'Tallahassee', area: Area.usa),
  const City(name: 'Huntsville', area: Area.usa),
  const City(name: 'Grand Prairie', area: Area.usa),
  const City(name: 'Knoxville', area: Area.usa),
  const City(name: 'Worcester', area: Area.usa),
  const City(name: 'Newport News', area: Area.usa),
  const City(name: 'Brownsville', area: Area.usa),
  const City(name: 'Overland Park', area: Area.usa),
  const City(name: 'Santa Rosa', area: Area.usa),
  const City(name: 'Garden Grove', area: Area.usa),
  const City(name: 'Vancouver', area: Area.usa),
  const City(name: 'Sioux Falls', area: Area.usa),
  const City(name: 'Ontario', area: Area.usa),
  const City(name: 'Chattanooga', area: Area.usa),
  const City(name: 'Tempe', area: Area.usa),
  const City(name: 'Oceanside', area: Area.usa),
  const City(name: 'McKinney', area: Area.usa),
  const City(name: 'Fort Lauderdale', area: Area.usa),
  const City(name: 'Cape Coral', area: Area.usa),
  const City(name: 'Shreveport', area: Area.usa),
  const City(name: 'Frisco', area: Area.usa),
  const City(name: 'Lubbock', area: Area.usa),
  const City(name: 'Irving', area: Area.usa),
  const City(name: 'Spokane', area: Area.usa),
  const City(name: 'Glendale', area: Area.usa),
  const City(name: 'Hialeah', area: Area.usa),
  const City(name: 'Fremont', area: Area.usa),
  const City(name: 'Richmond', area: Area.usa),
  const City(name: 'Boise', area: Area.usa),
  const City(name: 'San Bernardino', area: Area.usa),
  const City(name: 'Baton Rouge', area: Area.usa),
  const City(name: 'Des Moines', area: Area.usa),
  const City(name: 'Tacoma', area: Area.usa),
  const City(name: 'Santa Clarita', area: Area.usa),
  const City(name: 'Moreno Valley', area: Area.usa),
  const City(name: 'Glendale', area: Area.usa),
  const City(name: 'Rochester', area: Area.usa),
  const City(name: 'Modesto', area: Area.usa),
  const City(name: 'Fontana', area: Area.usa),
  const City(name: 'Oxnard', area: Area.usa),
  const City(name: 'Birmingham', area: Area.usa),
  const City(name: 'Salt Lake City', area: Area.usa),
  const City(name: 'Amarillo', area: Area.usa),
  const City(name: 'Montgomery', area: Area.usa),
  const City(name: 'Little Rock', area: Area.usa),
  const City(name: 'Akron', area: Area.usa),
  const City(name: 'Grand Rapids', area: Area.usa),
  const City(name: 'Tallahassee', area: Area.usa),
  const City(name: 'Huntsville', area: Area.usa),
  const City(name: 'Newport News', area: Area.usa),
  const City(name: 'Grand Prairie', area: Area.usa),
  const City(name: 'Knoxville', area: Area.usa),
  const City(name: 'Brownsville', area: Area.usa),
  const City(name: 'Overland Park', area: Area.usa),
  const City(name: 'Sioux Falls', area: Area.usa),
  const City(name: 'Oceanside', area: Area.usa),
  const City(name: 'Chattanooga', area: Area.usa),
  const City(name: 'Tempe', area: Area.usa),
  const City(name: 'Frisco', area: Area.usa),
  const City(name: 'McKinney', area: Area.usa),
  const City(name: 'Fort Lauderdale', area: Area.usa),
  const City(name: 'Cape Coral', area: Area.usa),
  const City(name: 'Shreveport', area: Area.usa),
  const City(name: 'Vancouver', area: Area.usa),
  // Sweden cities
  const City(name: 'Stockholm', area: Area.sweden),
  const City(name: 'Gothenburg', area: Area.sweden),
  const City(name: 'Malmö', area: Area.sweden),
  const City(name: 'Uppsala', area: Area.sweden),
  const City(name: 'Västerås', area: Area.sweden),
  const City(name: 'Örebro', area: Area.sweden),
  const City(name: 'Linköping', area: Area.sweden),
  const City(name: 'Helsingborg', area: Area.sweden),
  const City(name: 'Jönköping', area: Area.sweden),
  const City(name: 'Norrköping', area: Area.sweden),
  const City(name: 'Lund', area: Area.sweden),
  const City(name: 'Umeå', area: Area.sweden),
  const City(name: 'Gävle', area: Area.sweden),
  const City(name: 'Borås', area: Area.sweden),
  const City(name: 'Södertälje', area: Area.sweden),
  const City(name: 'Eskilstuna', area: Area.sweden),
  const City(name: 'Karlstad', area: Area.sweden),
  const City(name: 'Täby', area: Area.sweden),
  const City(name: 'Växjö', area: Area.sweden),
  const City(name: 'Halmstad', area: Area.sweden),
  const City(name: 'Sundsvall', area: Area.sweden),
  const City(name: 'Luleå', area: Area.sweden),
  const City(name: 'Trollhättan', area: Area.sweden),
  const City(name: 'Kalmar', area: Area.sweden),
  const City(name: 'Skövde', area: Area.sweden),
  const City(name: 'Karlskrona', area: Area.sweden),
  const City(name: 'Kristianstad', area: Area.sweden),
  const City(name: 'Borlänge', area: Area.sweden),
  const City(name: 'Boden', area: Area.sweden),
  const City(name: 'Trelleborg', area: Area.sweden),
  const City(name: 'Västervik', area: Area.sweden),
  const City(name: 'Nyköping', area: Area.sweden),
  const City(name: 'Katrineholm', area: Area.sweden),
  const City(name: 'Mariestad', area: Area.sweden),
  const City(name: 'Uddevalla', area: Area.sweden),
  const City(name: 'Falun', area: Area.sweden),
  const City(name: 'Karlshamn', area: Area.sweden),
  const City(name: 'Ängelholm', area: Area.sweden),
  const City(name: 'Lidingö', area: Area.sweden),
  const City(name: 'Piteå', area: Area.sweden),
  const City(name: 'Värnamo', area: Area.sweden),
  const City(name: 'Falköping', area: Area.sweden),
  const City(name: 'Motala', area: Area.sweden),
  const City(name: 'Sandviken', area: Area.sweden),
  const City(name: 'Hudiksvall', area: Area.sweden),
  const City(name: 'Falkenberg', area: Area.sweden),
  const City(name: 'Vimmerby', area: Area.sweden),
  const City(name: 'Åmål', area: Area.sweden),
  const City(name: 'Kiruna', area: Area.sweden),
  const City(name: 'Mora', area: Area.sweden),
  const City(name: 'Ystad', area: Area.sweden),
  const City(name: 'Ronneby', area: Area.sweden),
  const City(name: 'Härnösand', area: Area.sweden),
  const City(name: 'Ljungby', area: Area.sweden),
  const City(name: 'Alingsås', area: Area.sweden),
  const City(name: 'Nässjö', area: Area.sweden),
  const City(name: 'Sigtuna', area: Area.sweden),
  const City(name: 'Kumla', area: Area.sweden),
  const City(name: 'Arvika', area: Area.sweden),
  const City(name: 'Höör', area: Area.sweden),
  const City(name: 'Vansbro', area: Area.sweden),
  const City(name: 'Mjölby', area: Area.sweden),
  const City(name: 'Simrishamn', area: Area.sweden),
  const City(name: 'Torsby', area: Area.sweden),
  const City(name: 'Säffle', area: Area.sweden),
  const City(name: 'Hörby', area: Area.sweden),
  const City(name: 'Båstad', area: Area.sweden),
  const City(name: 'Haparanda', area: Area.sweden),
  const City(name: 'Eslöv', area: Area.sweden),
  const City(name: 'Lysekil', area: Area.sweden),
  const City(name: 'Ljungskile', area: Area.sweden),
  const City(name: 'Älvsbyn', area: Area.sweden),
  const City(name: 'Tomelilla', area: Area.sweden),
  const City(name: 'Svedala', area: Area.sweden),
  const City(name: 'Hallsberg', area: Area.sweden),
  const City(name: 'Tranås', area: Area.sweden),
  const City(name: 'Strömstad', area: Area.sweden),
  const City(name: 'Orsa', area: Area.sweden),
  const City(name: 'Sollefteå', area: Area.sweden),
  const City(name: 'Trosa', area: Area.sweden),
  const City(name: 'Smedjebacken', area: Area.sweden),
  const City(name: 'Eksjö', area: Area.sweden),
  const City(name: 'Bollnäs', area: Area.sweden),
  const City(name: 'Strängnäs', area: Area.sweden),
  const City(name: 'Köping', area: Area.sweden),
  const City(name: 'Skellefteå', area: Area.sweden),
  const City(name: 'Avesta', area: Area.sweden),
  const City(name: 'Söderhamn', area: Area.sweden),
  const City(name: 'Enköping', area: Area.sweden),
  const City(name: 'Kristinehamn', area: Area.sweden),
  const City(name: 'Åre', area: Area.sweden),
  const City(name: 'Malung', area: Area.sweden),
  const City(name: 'Vetlanda', area: Area.sweden),
  const City(name: 'Åtvidaberg', area: Area.sweden),
  const City(name: 'Ödeshög', area: Area.sweden),
  const City(name: 'Skara', area: Area.sweden),
  const City(name: 'Sunne', area: Area.sweden),
  const City(name: 'Herrljunga', area: Area.sweden),
  const City(name: 'Vaggeryd', area: Area.sweden),
  const City(name: 'Kävlinge', area: Area.sweden),
  const City(name: 'Järfälla', area: Area.sweden),
  const City(name: 'Sundbyberg', area: Area.sweden),
  const City(name: 'Sollentuna', area: Area.sweden),
  const City(name: 'Luleå', area: Area.sweden),
  const City(name: 'Haparanda', area: Area.sweden),
  // Australia cities
  const City(name: 'Sydney', area: Area.australia),
  const City(name: 'Melbourne', area: Area.australia),
  const City(name: 'Brisbane', area: Area.australia),
  const City(name: 'Perth', area: Area.australia),
  const City(name: 'Adelaide', area: Area.australia),
  const City(name: 'Gold Coast', area: Area.australia),
  const City(name: 'Canberra', area: Area.australia),
  const City(name: 'Hobart', area: Area.australia),
  const City(name: 'Darwin', area: Area.australia),
  const City(name: 'Cairns', area: Area.australia),
  const City(name: 'Townsville', area: Area.australia),
  const City(name: 'Toowoomba', area: Area.australia),
  const City(name: 'Geelong', area: Area.australia),
  const City(name: 'Wollongong', area: Area.australia),
  const City(name: 'Newcastle', area: Area.australia),
  const City(name: 'Bendigo', area: Area.australia),
  const City(name: 'Ballarat', area: Area.australia),
  const City(name: 'Mackay', area: Area.australia),
  const City(name: 'Rockhampton', area: Area.australia),
  const City(name: 'Bundaberg', area: Area.australia),
  const City(name: 'Launceston', area: Area.australia),
  const City(name: 'Albury', area: Area.australia),
  const City(name: 'Wagga Wagga', area: Area.australia),
  const City(name: 'Coffs Harbour', area: Area.australia),
  const City(name: 'Dubbo', area: Area.australia),
  const City(name: 'Orange', area: Area.australia),
  const City(name: 'Tamworth', area: Area.australia),
  const City(name: 'Bathurst', area: Area.australia),
  const City(name: 'Kalgoorlie', area: Area.australia),
  const City(name: 'Bunbury', area: Area.australia),
  const City(name: 'Geraldton', area: Area.australia),
  const City(name: 'Albany', area: Area.australia),
  const City(name: 'Mount Gambier', area: Area.australia),
  const City(name: 'Port Macquarie', area: Area.australia),
  const City(name: 'Mildura', area: Area.australia),
  const City(name: 'Gladstone', area: Area.australia),
  const City(name: 'Armidale', area: Area.australia),
  const City(name: 'Broken Hill', area: Area.australia),
  const City(name: 'Goulburn', area: Area.australia),
  const City(name: 'Bowral', area: Area.australia),
  const City(name: 'Griffith', area: Area.australia),
  const City(name: 'Warrnambool', area: Area.australia),
  const City(name: 'Shepparton', area: Area.australia),
  const City(name: 'Wangaratta', area: Area.australia),
  const City(name: 'Mount Isa', area: Area.australia),
  const City(name: 'Victor Harbor', area: Area.australia),
  const City(name: 'Alice Springs', area: Area.australia),
  const City(name: 'Whyalla', area: Area.australia),
  const City(name: 'Devonport', area: Area.australia),
  const City(name: 'Burnie', area: Area.australia),
  const City(name: 'Grafton', area: Area.australia),
  const City(name: 'Lithgow', area: Area.australia),
  const City(name: 'Warwick', area: Area.australia),
  const City(name: 'Emerald', area: Area.australia),
  const City(name: 'Maryborough', area: Area.australia),
  const City(name: 'Horsham', area: Area.australia),
  const City(name: 'Gympie', area: Area.australia),
  const City(name: 'Charters Towers', area: Area.australia),
  const City(name: 'Karratha', area: Area.australia),
  const City(name: 'Broome', area: Area.australia),
  const City(name: 'Exmouth', area: Area.australia),
  const City(name: 'Esperance', area: Area.australia),
  const City(name: 'Port Hedland', area: Area.australia),
  const City(name: 'Katherine', area: Area.australia),
  const City(name: 'Wyndham', area: Area.australia),
  const City(name: 'Manjimup', area: Area.australia),
  const City(name: 'Margaret River', area: Area.australia),
  const City(name: 'Smithton', area: Area.australia),
  const City(name: 'Queenstown', area: Area.australia),
  const City(name: 'Zeehan', area: Area.australia),
];
