name: bloc_demo_app
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  analytics_repository:
    path: packages/analytics_repository
  app_logging:
    path: packages/app_logging
  bloc_concurrency: ^0.2.5
  city_repository:
    path: packages/city_repository
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  go_router: ^14.3.0
  provider: ^6.1.2
  skeletonizer: ^1.4.2
  stream_transform: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^6.0.0

flutter:
  uses-material-design: true
