name: app_logging
description: A package for configurable logging. Includes Sentry integration (must be added manually).
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  logging: ^1.2.0

dev_dependencies:
  mocktail: ^1.0.4
  test: ^1.25.2
  very_good_analysis: ^6.0.0
